# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
'''
list(a)只會轉換表層元素為list，如果array有多層的話，只會賺患第一層
tolist()會把每層元素轉換成list
'''

'\nYour Code\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [1]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [4]:

a = np.random.randint(10, size=6) 


print(a)#顯示矩陣
print(a.ndim)#顯示維度大小
print(a.shape)#顯示每個維度元素數量
print(a.size)#顯示矩陣內元素總數量
print(a.dtype)#顯示矩陣內元素資料型態
print(a.itemsize)#顯示矩陣內每個元素所佔記憶體空間
print(len(a))#顯示最外層元素總數
print(type(a))#顯示矩陣的資料型態

[0 3 4 5 5 0]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [ ]:
b = np.random.randint(10, size=(3,4)) 


print(b)#顯示矩陣
print(b.ndim)#顯示維度大小
print(b.shape)#顯示每個維度元素數量
print(b.size)#顯示矩陣內元素總數量
print(b.dtype)#顯示矩陣內元素資料型態
print(b.itemsize)#顯示矩陣內每個元素所佔記憶體空間
print(len(b))#顯示最外層元素總數
print(type(b))#顯示矩陣的資料型態

[[0 7 9 3]
 [8 2 7 7]
 [9 3 3 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 


print(c)#顯示矩陣
print(c.ndim)#顯示維度大小
print(c.shape)#顯示每個維度元素數量
print(c.size)#顯示矩陣內元素總數量
print(c.dtype)#顯示矩陣內元素資料型態
print(c.itemsize)#顯示矩陣內每個元素所佔記憶體空間
print(len(c))#顯示最外層元素總數
print(type(c))#顯示矩陣的資料型態

[[[1 3]
  [2 8]
  [2 5]]

 [[0 0]
  [8 0]
  [1 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [8]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[6, 4, 0, 4, 6, 5]
[6, 4, 0, 4, 6, 5]


In [14]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 4, 7, 4], [3, 6, 5, 2], [7, 7, 2, 3]]
[array([5, 4, 7, 4]), array([3, 6, 5, 2]), array([7, 7, 2, 3])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [ ]:
def tolist(iterable):
    n = iterable.ndim
    for i in range(n-1):
        iterable = list()
        

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
